Issue 211: Extract chat messages logic to separate class
jmakhack/hydrate-reminder pull request #218
Opened 2022-09-24 13:04 UTC by macslowiak

## Associated Issue
Closes #211 

## Implemented Solution
Chat messages was extracted to ChatMessageSender class.
Additionally some methods related to chat messages was extracted to ChatMessageTypeProvider and HydrateEmojiProvider classes.

## Testing Details
Unit tests included. Chat messages are still working - screenshot.

Operating System: Windows 11
RuneLite Version: 1.8.33.3

## Screenshots
![image](https://user-images.githubusercontent.com/94566117/192099512-3182a73b-470f-47af-8b2b-62d331690449.png)

2022-09-24 15:38 UTC, mslowiak commented
@jmakhack I will take a look tomorrow at this one

2022-09-25 13:43 UTC, mslowiak requested changes
Cool stuff @macslowiak 🚀 
I have just two comments that should be addressed in this PR 👍

2022-09-25 13:43 UTC, mslowiak commented on src/main/java/com/hydratereminder/command/chat/ChatMessageSender.java
> +package com.hydratereminder.command.chat;
Would be great to have those classes under `com.hydratereminder.chat` instead of `com.hydratereminder.command.chat` :)

2022-09-25 13:43 UTC, mslowiak commented on src/main/java/com/hydratereminder/command/chat/ChatMessageSender.java
> +    public void sendHydrateEmojiChatMessage(ChatMessageType type, String message) {
Class `HydrateReminderPlugin` uses this method always with `ChatMessageType.GAMEMESSAGE` argument.

Can we make this method private, and expose another one like `sendHydrateEmojiChatGameMessage` that will utilize this implementation? 

The the signature of methods in `HydrateReminderPlugin` will be just:
```
chatMessageSender.sendHydrateEmojiChatGameMessage(message);
```

2022-09-25 19:14 UTC, mslowiak approved these changes
LGTM @jmakhack

2022-09-25 22:41 UTC, jmakhack commented
@all-contributors please add @macslowiak for code and tests

2022-09-26 00:03 UTC, jmakhack approved these changes
The code looks good and I confirmed all the chat message settings within Runelite are working as expected. Good work!

2022-09-26 00:04 UTC, merged